### PR TITLE
Fix: Stop treating completely failed network requests as successes

### LINKED ISSUE #5: Properly handle connection errors
Make sure this fires the callback with an `err` argument if the internet is offline, or for some other reason it was not possible to send the proxy request.

### PR DESCRIPTION
**Pull request by dmsnell**
Resolves #5

When certain network requests fail because the internet connection is completely broken they are coming through as if they were successes and the passed callback is called with `(err = null, data = {})`. This breaks the application logic which depends on failing requests actually failing.

I added the strict-equality check on the returned `statusCode` because I noticed that when the network connection was severed it was coming back with a value of `0` and not `null`. This appears to fix the problem I'm observing.

On the other hand, it's not clear to me when the status would be `null` or why this check is in there to begin with. I'm not sure what other things could be breaking as a result of this change. Would really appreciate some review and some insight into this odd behavior.

Thanks!

### CODE REVIEW

**Comment by nb** [comment]
@dmsnell, after looking through few of the linked issues I couldn't find specific reproduction steps. Without them it's unclear whether the PR solves a specific problem.

**Comment by blowery** [comment]
> I added the strict-equality check on the returned statusCode because I noticed that when the network connection was severed it was coming back with a value of 0 and not null. This appears to fix the problem I'm observing.

Could you elaborate on how this PR fixes the issue? I think I'm missing something, because `null == 0` is `false`. `null === 0` is also `false`. How does switching to strict equality help here?

**Comment by dmsnell** [comment]
@nb and @blowery this also resolves an issue in Automattic/wp-calypso#15636 whereby on failed network connections we were reporting that an upload was successful.

the problem is that while the status code comes across as `0`, it coerces to `null` and therefore the library thinks it must have been a successful request without a status code.

I don't know _when_ we would get a `null` status code but in my testing I found `0` to be reliably what is returned when the network connection is off. This loss of information is due to the limited props being passed through the `postMessage()` from the proxy iframe to the parent iframe.

To reproduce, find any `wpcom.js` code using `wpcom-proxy-request` and attempt to make a connection which the network off (I used Chrome's network throttling in the "Offline" state). The callback should return with a `null` error and an empty object as the `data` param, which signals a success. This carries through to the returned Promise as well since it uses the same `if ( error ) { reject( error ) }` logic that the callback code uses.

Hope that clears up the problem and reproduction steps. See [the linked PR](https://github.com/Automattic/wp-calypso/pull/15636/files#diff-a23bf110d34387bc8ec0357f19076e0dR33) for the discovery point.

**Comment by blowery** [comment]
> the problem is that while the status code comes across as 0, it coerces to null and therefore the library thinks it must have been a successful request without a status code.

where does that happen?

**Comment by blowery** [comment]
ahhhh https://github.com/Automattic/wpcom-proxy-request/pull/20/files#diff-168726dbe96b3ce427e7fedce31bb0bcL445

so we don't set `statusCode` if the value is falsey and 0 is falsey.

**Comment by dmsnell** [comment]
All in all @blowery I think this library could use some major rework as it seemed like much of the code here and in the corresponding public-api.wordpress.com module was build on some pretty old standards. since it's mostly working, of course, I don't predict this happening soon.

it would be nice to enumerate browser compatibility here too. do we support older browsers than most of our other products? (note, for example, the use of `component-event`)

**Comment by blowery** [comment]
so, is adding the explicit null check the right course, or should we add a check for `0` up above at line 445?

**Comment by blowery** [comment]
My assumption is that a `null == val` check is supposed to be a `is the val null or undefined`. The question this raises for me is "when would the statusCode be undefined and the request be successful". Perhaps @retrofox remembers?

**Comment by coderkevin** [comment]
> My assumption is that a null == val check is supposed to be a is the val null or undefined

Seems to me that an explicit check for both of those values would be preferable then, if that's what we want.

**Comment by dmsnell** [comment]
I like @sirbrillig's suggestion that we only consider a success as a request with a successful status code.

**Comment by dmsnell** [comment]
one way we can find out about all this is to merge into staging and thoroughly test

**Comment by rralian** [comment]
> I like @sirbrillig's suggestion that we only consider a success as a request with a successful status code.

> one way we can find out about all this is to merge into staging and thoroughly test

I like that too. If we have some weird case where the status code is not `2xx` and we still want to consider it a success, then we should find and fix that rather than code around it.

**Comment by coderkevin** [comment]
I like the idea of requiring a 2xx to be considered successful. I guess the question is, what code out there is expecting a "success" without a 2xx and how will it break if this changes?

**Comment by sirbrillig** [comment]
I think the only way to find out is to try. Since it's technically a breaking change, maybe it's worth bumping the major version. Then anyone who wishes to update will know what they're getting into.

**Comment by coderkevin** [comment]
What else out there depends on this other than WordPress.com / Calypso?

**Comment by sirbrillig** [comment]
@gwwar bumping to 3.2 would only imply adding features, not a breaking change, right? I think it would need to be 4.0. But in any case we should publish an alpha version for use in calypso.

**Comment by gwwar** [comment]
If we think it's that risky, then yes `4.0` would be more appropriate.

**Comment by gwwar** [comment]
To publish an alpha we'll need one of the npm owners to do so. So @retrofox, @skeltoac, @nylen, @timmyc, or @TooTallNate

**Comment by sirbrillig** [comment]
@dmsnell want to change this to `( statusCode && 2 === Math.floor( statusCode / 100 ) )`?

**Comment by sirbrillig** [comment]
> if we think it's that risky, then yes 4.0 would be more appropriate.

It seems like a small change to bump a major version number. I don't know if it's necessary but I think it's worth discussion (although I don't want to impact merging or testing this in Calypso) because in the very odd chance that someone is relying on this behavior, we could be breaking any number of flows.

**Comment by dmsnell** [comment]
My plan is to create a Calypso PR on Monday for this branch so we can test. If the tests go well we can merge here and then update Calypso with a version-bump PR.

Please vote if you agree or disagree.

**Comment by gwwar** [comment]
Steps to publish an alpha:
1. bump package.json version to `4.0.0-alpha.1` and commit it to this branch
2. package owner does `npm publish --tag next` in this branch
3. in https://github.com/Automattic/wp-calypso/issues/16097 you can update versions by calling `npm install wpcom-proxy-request@next --save` make sure the shrinkwrap is also updated

**Comment by retrofox** [comment]
> bump package.json version to 4.0.0-alpha.1 and commit it to this branch
> package owner does npm publish --tag next in this branch

could I help with 1 and 2 @gwwar?

**Comment by retrofox** [comment]
Getting this issue https://github.com/npm/npm/issues/17463 when I try to publish

**Comment by retrofox** [comment]
`wpcom-proxy-request@4.0.0-alpha.1` is already published.

**Pull request merged**
