### PR TITLE
Fix Chrome file upload workaround to avoid breaking Safari 10

### PR DESCRIPTION
**Pull request by jsnajdr**
The `new File( ... )` trick to patch `File` object breaks file uploads on Safari 10. Safari then uploads empty files. This PR limits the patching to Chrome.

### CODE REVIEW

**Comment by blowery** [comment]
@sgomes the easiest way to test is inside calypso with `npm link`. 

1. `make build; npm link` in this repo
2. go to calypso, `npm link wpcom-proxy-request`
3. rebuild calypso
4. test!

**Comment by blowery** [comment]
Still works in chrome. :)

**Comment by jsnajdr** [comment]
Few more things to test:
- test that file uploads work in Safari 10 again (Browserstack is your friend)
- test Chromium based browsers like Vivaldi or Brave or Opera or...
- IE11 and Edge should continue to work, too.

**Comment by jsnajdr** [comment]
Argh! MS Edge exposes a `window.chrome` object, but obviously is not Chromium based and doesn't support `new File` constructor. Uploads fail. One more fixup will be needed 😡

**Comment by jsnajdr** [comment]
Fixed the Edge bug, tested on Vivaldi (doesn't work without this PR, works with it). Going to merge now and publish 5.0.2. There will be more opportunities to test in the Calypso PR that upgrades the package.

**Pull request merged**
