### PR TITLE
Update the rest-proxy URL to version 2.0 and release v5.0.0 version of the npm package

### PR DESCRIPTION
**Pull request by jsnajdr**
I'm trying to finish the long-awaited project to slim down the REST Proxy by removing the dependency on jQuery. The new version will be available at:
```
https://public-api.wordpress.com/wp-admin/rest-proxy/?v=2.0
```
This patch updates the `src` of the iframe that this module will load to the new URL.

We'll release this version of the package as 5.0.0, since there is quite major update of the server-side implementation (although its behavior is supposed to be unchanged).

### CODE REVIEW

**Comment by sirbrillig** [comment]
Is there any way to pass the option as a parameter to `request()` that gets passed along to `install()`? Or possibly some sort of factory that creates a new version of `request()` with the appropriate setting? It's been a while since I've been in this code, so this is just a suggestion. I know it's a little awkward, but I just wanted to consider other options without having to add state.

**Comment by sirbrillig** [comment]
(That said, this looks functional and I'm sure it will solve your situation.)

**Comment by jsnajdr** [comment]
> Is there any way to pass the option as a parameter to request() that gets passed along to install()?

I would have to pass the extra option to every request, because I don't know which one will be the first that triggers the iframe installation. Also, the `wpcom.request` call is hidden deep down various abstraction layers -- the Calypso code never calls it directly.

I think it's much easier to just import and call a function in `client/lib/wp/browser.js`.

**Comment by sirbrillig** [comment]
Yeah, I figured, but I had to at least try 😉 . 👍  Looks good to me.

**Comment by dmsnell** [comment]
Are we relying on clients to call this new function before `request()`? would it not make sense to reload the iframe after calling `setProxyVersion`?

Do we even need to expose that other function? Could we just as legitimately call `request()` differently?

The way I had originally planned on rolling this out is dependent on the idea that our goal is to have a single way of calling once we have verified that we don't introduce regressions. With that notion I had planned on just making the default in the version-bump here use the new version on the backend. That is, any clients upgrading to the next major version (to be introduced here) would get this beta script on the backend and when we're ready we can update our clients to use the new major release, until then keep it beta.

It seems like we [can publish beta releases](https://docs.npmjs.com/getting-started/using-tags) with `npm`.

```bash
npm publish --tag beta
```

**Comment by jsnajdr** [comment]
> Are we relying on clients to call this new function before `request()`? would it not make sense to reload the iframe after calling `setProxyVersion`?

The expected way to use the module is to import it, call `setProxyVersion` and then start issuing requests with the configured library:
```js
import request, { setProxyVersion } from 'wpcom-proxy-request';
setProxyVersion( '2.0' );
request( ... );
```

> Do we even need to expose that other function? Could we just as legitimately call `request()` differently?

We discussed this with @sirbrillig a few comments above. We want to first configure the proxy, and then start issuing requests to it. What would be the point of passing the initialization info to each request, even after the proxy is already initialized.

Also, the real `request()` calls are hidden deeply inside various abstraction layers (data layer, wpcom, Pinghub). It would be a lot of trouble to deliver the correct parameters there.

> With that notion I had planned on just making the default in the version-bump here use the new version on the backend.

I like this idea -- we could say that if someone chooses to use this particular release of the `wpcom-proxy-request` module, they get the 2.0 version of the iframe hardcoded, with zero configuration. Is that what you are suggesting?

**Comment by dmsnell** [comment]
> The expected way to use the module is to import it, call setProxyVersion and then start issuing requests with the configured library:

I think this would make for a great paragraph in the README :wink:

> if someone chooses to use this particular release of the wpcom-proxy-request module, they get the 2.0 version of the iframe hardcoded, with zero configuration. Is that what you are suggesting?

exactly. and by only publishing under the `beta` tag we can limit the exposure of the changes until we have had a change to build our confidence that it's all working

**Comment by jsnajdr** [comment]
@dmsnell I made the suggested changes: the `v=2.0` is now hardcoded in the URL, with zero-config, and the package version is bumped to 5.0.0. Please have a look.

**Pull request merged**
